'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WCFSvc
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="WCFsvc_.clsStockItem", [Namespace]:="http://schemas.datacontract.org/2004/07/IQ"),  _
     System.SerializableAttribute()>  _
    Partial Public Class WCFsvc_clsStockItem
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SKUField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SKUvariantField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private shipmentsField() As WCFSvc.WCFsvc_clsstock
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SKU() As String
            Get
                Return Me.SKUField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SKUField, value) <> true) Then
                    Me.SKUField = value
                    Me.RaisePropertyChanged("SKU")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SKUvariant() As String
            Get
                Return Me.SKUvariantField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SKUvariantField, value) <> true) Then
                    Me.SKUvariantField = value
                    Me.RaisePropertyChanged("SKUvariant")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property shipments() As WCFSvc.WCFsvc_clsstock()
            Get
                Return Me.shipmentsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.shipmentsField, value) <> true) Then
                    Me.shipmentsField = value
                    Me.RaisePropertyChanged("shipments")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="WCFsvc_.clsstock", [Namespace]:="http://schemas.datacontract.org/2004/07/IQ"),  _
     System.SerializableAttribute()>  _
    Partial Public Class WCFsvc_clsstock
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ArrivalField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QuantityField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Arrival() As Date
            Get
                Return Me.ArrivalField
            End Get
            Set
                If (Me.ArrivalField.Equals(value) <> true) Then
                    Me.ArrivalField = value
                    Me.RaisePropertyChanged("Arrival")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Quantity() As Integer
            Get
                Return Me.QuantityField
            End Get
            Set
                If (Me.QuantityField.Equals(value) <> true) Then
                    Me.QuantityField = value
                    Me.RaisePropertyChanged("Quantity")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="WCFsvc_.clsResult", [Namespace]:="http://schemas.datacontract.org/2004/07/IQ"),  _
     System.SerializableAttribute()>  _
    Partial Public Class WCFsvc_clsResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorCodeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SuccessField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorCode() As Integer
            Get
                Return Me.ErrorCodeField
            End Get
            Set
                If (Me.ErrorCodeField.Equals(value) <> true) Then
                    Me.ErrorCodeField = value
                    Me.RaisePropertyChanged("ErrorCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Success() As Boolean
            Get
                Return Me.SuccessField
            End Get
            Set
                If (Me.SuccessField.Equals(value) <> true) Then
                    Me.SuccessField = value
                    Me.RaisePropertyChanged("Success")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="WCFsvc_.clsPrice", [Namespace]:="http://schemas.datacontract.org/2004/07/IQ"),  _
     System.SerializableAttribute()>  _
    Partial Public Class WCFsvc_clsPrice
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CurrencyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GroupIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PriceField As Single
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SKUField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SKUvariantField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Currency() As String
            Get
                Return Me.CurrencyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CurrencyField, value) <> true) Then
                    Me.CurrencyField = value
                    Me.RaisePropertyChanged("Currency")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GroupID() As String
            Get
                Return Me.GroupIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GroupIDField, value) <> true) Then
                    Me.GroupIDField = value
                    Me.RaisePropertyChanged("GroupID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Price() As Single
            Get
                Return Me.PriceField
            End Get
            Set
                If (Me.PriceField.Equals(value) <> true) Then
                    Me.PriceField = value
                    Me.RaisePropertyChanged("Price")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SKU() As String
            Get
                Return Me.SKUField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SKUField, value) <> true) Then
                    Me.SKUField = value
                    Me.RaisePropertyChanged("SKU")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SKUvariant() As String
            Get
                Return Me.SKUvariantField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SKUvariantField, value) <> true) Then
                    Me.SKUvariantField = value
                    Me.RaisePropertyChanged("SKUvariant")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WCFSvc.iQuote_")>  _
    Public Interface iQuote_
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/iQuote_/SetStock", ReplyAction:="http://tempuri.org/iQuote_/SetStockResponse")>  _
        Function SetStock(ByVal SessionID As String, ByVal items() As WCFSvc.WCFsvc_clsStockItem) As WCFSvc.WCFsvc_clsResult()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/iQuote_/SetPrices", ReplyAction:="http://tempuri.org/iQuote_/SetPricesResponse")>  _
        Function SetPrices(ByVal SessionID As String, ByVal prices() As WCFSvc.WCFsvc_clsPrice) As WCFSvc.WCFsvc_clsResult()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface iQuote_Channel
        Inherits WCFSvc.iQuote_, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class iQuote_Client
        Inherits System.ServiceModel.ClientBase(Of WCFSvc.iQuote_)
        Implements WCFSvc.iQuote_
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function SetStock(ByVal SessionID As String, ByVal items() As WCFSvc.WCFsvc_clsStockItem) As WCFSvc.WCFsvc_clsResult() Implements WCFSvc.iQuote_.SetStock
            Return MyBase.Channel.SetStock(SessionID, items)
        End Function
        
        Public Function SetPrices(ByVal SessionID As String, ByVal prices() As WCFSvc.WCFsvc_clsPrice) As WCFSvc.WCFsvc_clsResult() Implements WCFSvc.iQuote_.SetPrices
            Return MyBase.Channel.SetPrices(SessionID, prices)
        End Function
    End Class
End Namespace
