//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Site
{

	///<summary>
	///HeadContent control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
	///<summary>
	///loginDisplay control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlGenericControl loginDisplay;
	///<summary>
	///LblRole control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label LblRole;
	///<summary>
	///newMenu control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlGenericControl newMenu;
	///<summary>
	///admMenu control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlGenericControl admMenu;
	///<summary>
	///accountSetting control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlGenericControl accountSetting;
	///<summary>
	///switchAccount control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlGenericControl switchAccount;
	///<summary>
	///Logout control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlGenericControl Logout;
	///<summary>
	///btnNav control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlGenericControl btnNav;
	///<summary>
	///btnPortFolio control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Button btnPortFolio;
	///<summary>
	///btnErrorDisplay control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Button btnErrorDisplay;
	///<summary>
	///BtnTreeMode control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Button BtnTreeMode;
	///<summary>
	///HyperBack control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.HyperLink HyperBack;
	///<summary>
	///newHeader control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlGenericControl newHeader;
	///<summary>
	///btnBrowse control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlGenericControl btnBrowse;
	///<summary>
	///searchMenuItem control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlAnchor searchMenuItem;
	///<summary>
	///toolsLink control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlGenericControl toolsLink;
	///<summary>
	///wareHouseli control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlGenericControl wareHouseli;
	///<summary>
	///btnContext control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlInputButton btnContext;
	///<summary>
	///xx control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlGenericControl xx;
	///<summary>
	///MainContent control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
	///<summary>
	///Label1 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label1;
	///<summary>
	///txtFeedBackFrom control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.TextBox txtFeedBackFrom;
	///<summary>
	///Label6 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label6;
	///<summary>
	///txtFeedbackName control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.TextBox txtFeedbackName;
	///<summary>
	///Label7 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label7;
	///<summary>
	///txtContactDetails control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.TextBox txtContactDetails;
	///<summary>
	///Label8 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label8;
	///<summary>
	///txtFeedbackLanguage control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.DropDownList txtFeedbackLanguage;
	///<summary>
	///Label2 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label2;
	///<summary>
	///feedbacktype control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.DropDownList feedbacktype;
	///<summary>
	///Label3 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label3;
	///<summary>
	///txtFeedback control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.TextBox txtFeedback;
	///<summary>
	///Label4 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label4;
	///<summary>
	///chkAllow control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.CheckBox chkAllow;
	///<summary>
	///btndiv control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlGenericControl btndiv;
	///<summary>
	///BtnFeedback control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Button BtnFeedback;
	///<summary>
	///lblMsg control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label lblMsg;
	///<summary>
	///Label5 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label5;
	///<summary>
	///drpLocation control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.DropDownList drpLocation;
	///<summary>
	///chkTax control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.CheckBoxList chkTax;
	///<summary>
	///drpWareHouse control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.DropDownList drpWareHouse;
	///<summary>
	///btnCancel control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Button btnCancel;
	///<summary>
	///btnContinue control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Button btnContinue;
	///<summary>
	///litSubmit control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Literal litSubmit;
	///<summary>
	///legalLink control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlInputButton legalLink;
	///<summary>
	///litVersion control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Literal litVersion;
	///<summary>
	///ttlMN control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlGenericControl ttlMN;
	///<summary>
	///terms control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>
	protected global::System.Web.UI.WebControls.Literal terms;
}
