//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Runtime.Serialization;

namespace GK
{

	[System.Diagnostics.DebuggerStepThroughAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"), System.Runtime.Serialization.DataContractAttribute(Name = "clsNameValuePair", Namespace = "http://schemas.datacontract.org/2004/07/IQ"), System.SerializableAttribute()]
	public partial class clsNameValuePair : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
	{

		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string NameField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string valueField;

		[System.ComponentModel.BrowsableAttribute(false)]
		public System.Runtime.Serialization.ExtensionDataObject System.Runtime.Serialization.IExtensibleDataObject.ExtensionData {
			get { return this.extensionDataField; }
			set { this.extensionDataField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Name {
			get { return this.NameField; }
			set {
				if ((object.ReferenceEquals(this.NameField, value) != true)) {
					this.NameField = value;
					this.RaisePropertyChanged("Name");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string value {
			get { return this.valueField; }
			set {
				if ((object.ReferenceEquals(this.valueField, value) != true)) {
					this.valueField = value;
					this.RaisePropertyChanged("value");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler System.ComponentModel.INotifyPropertyChanged.PropertyChanged;

		protected void RaisePropertyChanged(string propertyName)
		{
			System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChangedEvent;
			if ((!(propertyChanged) == null)) {
				propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"), System.Runtime.Serialization.DataContractAttribute(Name = "clsToken", Namespace = "http://schemas.datacontract.org/2004/07/IQ"), System.SerializableAttribute()]
	public partial class clsToken : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
	{

		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string[] ErrorsField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string ValueField;

		[System.ComponentModel.BrowsableAttribute(false)]
		public System.Runtime.Serialization.ExtensionDataObject System.Runtime.Serialization.IExtensibleDataObject.ExtensionData {
			get { return this.extensionDataField; }
			set { this.extensionDataField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string[] Errors {
			get { return this.ErrorsField; }
			set {
				if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
					this.ErrorsField = value;
					this.RaisePropertyChanged("Errors");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Value {
			get { return this.ValueField; }
			set {
				if ((object.ReferenceEquals(this.ValueField, value) != true)) {
					this.ValueField = value;
					this.RaisePropertyChanged("Value");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler System.ComponentModel.INotifyPropertyChanged.PropertyChanged;

		protected void RaisePropertyChanged(string propertyName)
		{
			System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChangedEvent;
			if ((!(propertyChanged) == null)) {
				propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"), System.Runtime.Serialization.DataContractAttribute(Name = "clsName", Namespace = "http://schemas.datacontract.org/2004/07/IQ"), System.SerializableAttribute()]
	public partial class clsName : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
	{

		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string ExampleField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private int MaxLengthField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private int MinLengthField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string NotesField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string RegExField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool RequiredField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string nameField;

		[System.ComponentModel.BrowsableAttribute(false)]
		public System.Runtime.Serialization.ExtensionDataObject System.Runtime.Serialization.IExtensibleDataObject.ExtensionData {
			get { return this.extensionDataField; }
			set { this.extensionDataField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Example {
			get { return this.ExampleField; }
			set {
				if ((object.ReferenceEquals(this.ExampleField, value) != true)) {
					this.ExampleField = value;
					this.RaisePropertyChanged("Example");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public int MaxLength {
			get { return this.MaxLengthField; }
			set {
				if ((this.MaxLengthField.Equals(value) != true)) {
					this.MaxLengthField = value;
					this.RaisePropertyChanged("MaxLength");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public int MinLength {
			get { return this.MinLengthField; }
			set {
				if ((this.MinLengthField.Equals(value) != true)) {
					this.MinLengthField = value;
					this.RaisePropertyChanged("MinLength");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Notes {
			get { return this.NotesField; }
			set {
				if ((object.ReferenceEquals(this.NotesField, value) != true)) {
					this.NotesField = value;
					this.RaisePropertyChanged("Notes");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string RegEx {
			get { return this.RegExField; }
			set {
				if ((object.ReferenceEquals(this.RegExField, value) != true)) {
					this.RegExField = value;
					this.RaisePropertyChanged("RegEx");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public bool Required {
			get { return this.RequiredField; }
			set {
				if ((this.RequiredField.Equals(value) != true)) {
					this.RequiredField = value;
					this.RaisePropertyChanged("Required");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string name {
			get { return this.nameField; }
			set {
				if ((object.ReferenceEquals(this.nameField, value) != true)) {
					this.nameField = value;
					this.RaisePropertyChanged("name");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler System.ComponentModel.INotifyPropertyChanged.PropertyChanged;

		protected void RaisePropertyChanged(string propertyName)
		{
			System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChangedEvent;
			if ((!(propertyChanged) == null)) {
				propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"), System.ServiceModel.ServiceContractAttribute(Namespace = "channelcentral.net/oneTimeToken", ConfigurationName = "GK.IOneTimeToken")]
	public interface IOneTimeToken
	{

		[System.ServiceModel.OperationContractAttribute(Action = "channelcentral.net/oneTimeToken/IOneTimeToken/GetToken", ReplyAction = "channelcentral.net/oneTimeToken/IOneTimeToken/GetTokenResponse")]
		GK.clsToken GetToken(string HostID, string HostPassword, GK.clsNameValuePair[] Pairs);

		[System.ServiceModel.OperationContractAttribute(Action = "channelcentral.net/oneTimeToken/IOneTimeToken/GetToken", ReplyAction = "channelcentral.net/oneTimeToken/IOneTimeToken/GetTokenResponse")]
		System.Threading.Tasks.Task<GK.clsToken> GetTokenAsync(string HostID, string HostPassword, GK.clsNameValuePair[] Pairs);

		[System.ServiceModel.OperationContractAttribute(Action = "channelcentral.net/oneTimeToken/IOneTimeToken/Help", ReplyAction = "channelcentral.net/oneTimeToken/IOneTimeToken/HelpResponse")]
		GK.clsName[] Help();

		[System.ServiceModel.OperationContractAttribute(Action = "channelcentral.net/oneTimeToken/IOneTimeToken/Help", ReplyAction = "channelcentral.net/oneTimeToken/IOneTimeToken/HelpResponse")]
		System.Threading.Tasks.Task<GK.clsName[]> HelpAsync();
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	public interface IOneTimeTokenChannel : GK.IOneTimeToken, System.ServiceModel.IClientChannel
	{
	}

	[System.Diagnostics.DebuggerStepThroughAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	public partial class OneTimeTokenClient : System.ServiceModel.ClientBase<GK.IOneTimeToken>, GK.IOneTimeToken
	{

		public OneTimeTokenClient()
		{
			base.New();
		}

		public OneTimeTokenClient(string endpointConfigurationName)
		{
			base.New(endpointConfigurationName);
		}

		public OneTimeTokenClient(string endpointConfigurationName, string remoteAddress)
		{
			base.New(endpointConfigurationName, remoteAddress);
		}

		public OneTimeTokenClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress)
		{
			base.New(endpointConfigurationName, remoteAddress);
		}

		public OneTimeTokenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress)
		{
			base.New(binding, remoteAddress);
		}

		public GK.clsToken GK.IOneTimeToken.GetToken(string HostID, string HostPassword, GK.clsNameValuePair[] Pairs)
		{
			return base.Channel.GetToken(HostID, HostPassword, Pairs);
		}

		public System.Threading.Tasks.Task<GK.clsToken> GK.IOneTimeToken.GetTokenAsync(string HostID, string HostPassword, GK.clsNameValuePair[] Pairs)
		{
			return base.Channel.GetTokenAsync(HostID, HostPassword, Pairs);
		}

		public GK.clsName[] GK.IOneTimeToken.Help()
		{
			return base.Channel.Help;
		}

		public System.Threading.Tasks.Task<GK.clsName[]> GK.IOneTimeToken.HelpAsync()
		{
			return base.Channel.HelpAsync;
		}
	}
}
