//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class NewAccount
{

	///<summary>
	///form1 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlForm form1;
	///<summary>
	///BtnCancel control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Button BtnCancel;
	///<summary>
	///Label5 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label5;
	///<summary>
	///Label6 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label6;
	///<summary>
	///TxtCompany control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.TextBox TxtCompany;
	///<summary>
	///Label1 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label1;
	///<summary>
	///TxtName control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.TextBox TxtName;
	///<summary>
	///Label2 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label2;
	///<summary>
	///TxtEmail control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.TextBox TxtEmail;
	///<summary>
	///Label3 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label3;
	///<summary>
	///TxtpriceBand control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.TextBox TxtpriceBand;
	///<summary>
	///Label4 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label4;
	///<summary>
	///chkWelcome control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.CheckBox chkWelcome;
	///<summary>
	///BtnGo control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>
	protected global::System.Web.UI.WebControls.Button BtnGo;
}
