//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class WebForm1
{

	///<summary>
	///Pnl control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Panel Pnl;
	///<summary>
	///PnlMultiSend control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Panel PnlMultiSend;
	///<summary>
	///Label10 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label10;
	///<summary>
	///txtMultiHost control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.TextBox txtMultiHost;
	///<summary>
	///btnGetStubs control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Button btnGetStubs;
	///<summary>
	///TxtMultisend control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.TextBox TxtMultisend;
	///<summary>
	///BtnMultisend control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Button BtnMultisend;
	///<summary>
	///chkMultiDoit control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.CheckBox chkMultiDoit;
	///<summary>
	///grdUser control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.GridView grdUser;
	///<summary>
	///grdActivity control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.GridView grdActivity;
	///<summary>
	///Label8 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label8;
	///<summary>
	///drpTeams control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.DropDownList drpTeams;
	///<summary>
	///Label4 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label4;
	///<summary>
	///txtEmailName control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.TextBox txtEmailName;
	///<summary>
	///drpDomain control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.DropDownList drpDomain;
	///<summary>
	///Label1 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label1;
	///<summary>
	///txtFullName control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.TextBox txtFullName;
	///<summary>
	///Label3 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label3;
	///<summary>
	///TxtTelephone control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.TextBox TxtTelephone;
	///<summary>
	///Label2 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label2;
	///<summary>
	///drpCurrency control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.DropDownList drpCurrency;
	///<summary>
	///chkAdminUser control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.CheckBox chkAdminUser;
	///<summary>
	///chkEmailUser control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.CheckBox chkEmailUser;
	///<summary>
	///chkEmailAdmin control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.CheckBox chkEmailAdmin;
	///<summary>
	///PnlHostOverride control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Panel PnlHostOverride;
	///<summary>
	///txtHostOverride control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.TextBox txtHostOverride;
	///<summary>
	///BtnSave control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>
	protected global::System.Web.UI.WebControls.Button BtnSave;
}
