//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class edit1
{

	///<summary>
	///form1 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>
	protected global::System.Web.UI.HtmlControls.HtmlForm form1;

	///<summary>
	///drpLanguage control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>
	protected global::System.Web.UI.WebControls.DropDownList drpLanguage;

	///<summary>
	///EditPanel control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>
	protected global::System.Web.UI.WebControls.Panel EditPanel;
}
