//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class tree1
{

	///<summary>
	///Label12 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label12;
	///<summary>
	///txtBuyer control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.TextBox txtBuyer;
	///<summary>
	///txtBuyerID control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.TextBox txtBuyerID;
	///<summary>
	///BtnStartQuote control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Button BtnStartQuote;
	///<summary>
	///PnlAddContact control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Panel PnlAddContact;
	///<summary>
	///Label1 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label1;
	///<summary>
	///Label2 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label2;
	///<summary>
	///Label3 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label Label3;
	///<summary>
	///focusPanel control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Panel focusPanel;
	///<summary>
	///FocusLabel control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label FocusLabel;
	///<summary>
	///FocusButton control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Button FocusButton;
	///<summary>
	///pnlQuoteTools control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Panel pnlQuoteTools;
	///<summary>
	///txtQuoteName control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.TextBox txtQuoteName;
	///<summary>
	///Btnsave control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Button Btnsave;
	///<summary>
	///btnXMLQuote control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Button btnXMLQuote;
	///<summary>
	///LblSave control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Label LblSave;
	///<summary>
	///BtnExcel control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Button BtnExcel;
	///<summary>
	///BtnPDF control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Button BtnPDF;
	///<summary>
	///BtnCopy control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Button BtnCopy;
	///<summary>
	///BtnEmail control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Button BtnEmail;
	///<summary>
	///PnlErrors control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Panel PnlErrors;
	///<summary>
	///litAdvert control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Literal litAdvert;
	///<summary>
	///warehousePanel control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Panel warehousePanel;
	///<summary>
	///treeHolder control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Panel treeHolder;
	///<summary>
	///PnlPriceCheck control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>
	protected global::System.Web.UI.WebControls.Panel PnlPriceCheck;
}
