'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Universal

    '''<summary>
    '''univSubheading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents univSubheading As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''univSubtitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents univSubtitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''univInstructions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents univInstructions As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''panelManufacturer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelManufacturer As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''panelHPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelHPI As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''panelHPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelHPE As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''panelBanner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelBanner As Global.System.Web.UI.WebControls.Panel
End Class
