
-- Create PLCodeLookup table 
CREATE TABLE [dbo].[PLCodeLookup](
	[plCode] [nvarchar](2) NOT NULL,
	[mfrCode] [nvarchar](3) NOT NULL,
 CONSTRAINT [PK_PLCodeLookup] PRIMARY KEY CLUSTERED 
(
	[plCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


-- Populate PLCodeLookup table
insert into [PLCodeLookup] (plCode, mfrCode)
values
 ('6', 'HPE')
,('7', 'HPI')
,('8', 'HPE')
,('1N', 'HPI')
,('1U', 'HPE')
,('1Y', 'HPE')
,('21', 'HPI')
,('2A', 'HPI')
,('2B', 'HPI')
,('2C', 'HPI')
,('2G', 'HPI')
,('2H', 'HPI')
,('2N', 'HPI')
,('2P', 'HPI')
,('2Q', 'HPI')
,('30', 'HPI')
,('31', 'HPI')
,('32', 'HPI')
,('33', 'HPI')
,('34', 'HPI')
,('35', 'HPE')
,('3C', 'HPE')
,('3P', 'HPE')
,('3S', 'HPE')
,('3V', 'HPE')
,('3Y', 'HPI')
,('43', 'HPE')
,('4A', 'HPE')
,('4H', 'HPI')
,('4M', 'HPI')
,('4Q', 'HPE')
,('4T', 'HPI')
,('4U', 'HPE')
,('4X', 'HPI')
,('52', 'HPI')
,('5M', 'HPI')
,('5T', 'HPI')
,('5U', 'HPI')
,('5X', 'HPI')
,('6A', 'HPI')
,('6H', 'HPE')
,('6J', 'HPI')
,('6L', 'HPE')
,('6U', 'HPI')
,('6V', 'HPI')
,('6W', 'HPE')
,('7A', 'HPE')
,('7F', 'HPI')
,('7G', 'HPE')
,('7S', 'HPI')
,('7T', 'HPI')
,('7U', 'HPI')
,('7X', 'HPI')
,('83', 'HPI')
,('8A', 'HPI')
,('8J', 'HPI')
,('96', 'HPE')
,('9C', 'HPI')
,('9F', 'HPI')
,('9G', 'HPI')
,('9H', 'HPI')
,('9J', 'HPI')
,('A5', 'HPI')
,('AK', 'HPI')
,('AN', 'HPI')
,('AU', 'HPI')
,('BO', 'HPI')
,('C2', 'HPI')
,('C5', 'HPI')
,('DA', 'HPI')
,('DC', 'HPI')
,('DL', 'HPI')
,('DU', 'HPI')
,('EX', 'HPI')
,('EZ', 'HPI')
,('I5', 'HPE')
,('I7', 'HPE')
,('I8', 'HPE')
,('I9', 'HPE')
,('J2', 'HPE')
,('J3', 'HPE')
,('JN', 'HPE')
,('K2', 'HPI')
,('K3', 'HPE')
,('K4', 'HPI')
,('K5', 'HPI')
,('K6', 'HPI')
,('K7', 'HPI')
,('K8', 'HPI')
,('K9', 'HPI')
,('KN', 'HPI')
,('KP', 'HPI')
,('KV', 'HPI')
,('KX', 'HPI')
,('LA', 'HPE')
,('LF', 'HPI')
,('LH', 'HPE')
,('LI', 'HPE')
,('LJ', 'HPE')
,('LK', 'HPE')
,('LL', 'HPE')
,('LM', 'HPE')
,('LN', 'HPE')
,('LY', 'HPI')
,('MA', 'HPI')
,('MB', 'HPI')
,('MC', 'HPI')
,('MG', 'HPI')
,('MN', 'HPI')
,('MP', 'HPI')
,('MV', 'HPE')
,('NW', 'HPE')
,('PQ', 'HPI')
,('R4', 'HPI')
,('R5', 'HPI')
,('R6', 'HPI')
,('R8', 'HPE')
,('R9', 'HPI')
,('SB', 'HPI')
,('SF', 'HPI')
,('SI', 'HPE')
,('ST', 'HPI')
,('SY', 'HPE')
,('T2', 'HPI')
,('T5', 'HPI')
,('T8', 'HPI')
,('TA', 'HPI')
,('TB', 'HPI')
,('TN', 'HPE')
,('TR', 'HPE')
,('TW', 'HPI')
,('TX', 'HPI')
,('UH', 'HPI')
,('UK', 'HPI')
,('UR', 'HPI')
,('US', 'HPI')
,('UT', 'HPI')
,('UU', 'HPI')
,('UV', 'HPI')
,('UW', 'HPE')
,('UZ', 'HPE')
GO
