// VBConversions Note: VB project level imports
using System.Text.RegularExpressions;
using System.Web.UI.HtmlControls;
using System.Diagnostics;
using System.Xml.Linq;
using System.Collections.Generic;
using System.Data;
using System.Collections.Specialized;
using System.Web.Profile;
using Microsoft.VisualBasic;
using System.Configuration;
using System.Web.UI.WebControls;
using System.Collections;
using System;
using System.Web;
using System.Web.UI;
using System.Web.SessionState;
using System.Text;
using System.Web.Caching;
using System.Web.UI.WebControls.WebParts;
using System.Linq;
// End of VB project level imports


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQ
{


public partial class HpSignup
{

///<summary>
///header control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.HtmlControls.HtmlGenericControl header;

///<summary>
///LabelFullName control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.Label LabelFullName;

///<summary>
///txtFullName control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.TextBox txtFullName;

///<summary>
///LabelEmailName control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.Label LabelEmailName;

///<summary>
///txtEmailName control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.TextBox txtEmailName;

///<summary>
///LabelConfirmEmail control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.Label LabelConfirmEmail;

///<summary>
///txtConfirmEmail control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.TextBox txtConfirmEmail;

///<summary>
///LabelCompanyName control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.Label LabelCompanyName;

///<summary>
///txtCompanyName control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.TextBox txtCompanyName;

///<summary>
///LabelUserType control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.Label LabelUserType;

///<summary>
///ddlUserType control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.DropDownList ddlUserType;

///<summary>
///LabelPostCode control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.Label LabelPostCode;

///<summary>
///txtPostCode control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.TextBox txtPostCode;

///<summary>
///LabelTelephone control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.Label LabelTelephone;

///<summary>
///txtTelephone control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.TextBox txtTelephone;

///<summary>
///LabelREquiredField control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.Label LabelREquiredField;

///<summary>
///HeaderTandC control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.Literal HeaderTandC;

///<summary>
///litLegal control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.Literal litLegal;

///<summary>
///chkAgree control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.CheckBox chkAgree;

///<summary>
///BtnSave control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.Button BtnSave;

///<summary>
///BtnCancel control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.Button BtnCancel;

///<summary>
///litError control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.Literal litError;

///<summary>
///litRegistered control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.Literal litRegistered;

///<summary>
///litMsg control.
///</summary>
///<remarks>
///Auto-generated field.
///To modify move field declaration from designer file to code-behind file.
///</remarks>
protected global::System.Web.UI.WebControls.Literal litMsg;
}

}
