//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Runtime.Serialization;

namespace wsconsumer
{

	[System.Diagnostics.DebuggerStepThroughAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"), System.Runtime.Serialization.DataContractAttribute(Name = "clsStockPriceRequest", Namespace = "http://schemas.datacontract.org/2004/07/wsConsumer"), System.SerializableAttribute()]
	public partial class clsStockPriceRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
	{

		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string AdditionalParamsField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string AppField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string AuthKeyField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string CurrencyField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string HostAccountNumField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string HostIDField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string QuoteIDField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string SessionIDField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string UserIDField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string WarehouseField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string[] skusField;

		[System.ComponentModel.BrowsableAttribute(false)]
		public System.Runtime.Serialization.ExtensionDataObject System.Runtime.Serialization.IExtensibleDataObject.ExtensionData {
			get { return this.extensionDataField; }
			set { this.extensionDataField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string AdditionalParams {
			get { return this.AdditionalParamsField; }
			set {
				if ((object.ReferenceEquals(this.AdditionalParamsField, value) != true)) {
					this.AdditionalParamsField = value;
					this.RaisePropertyChanged("AdditionalParams");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string App {
			get { return this.AppField; }
			set {
				if ((object.ReferenceEquals(this.AppField, value) != true)) {
					this.AppField = value;
					this.RaisePropertyChanged("App");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string AuthKey {
			get { return this.AuthKeyField; }
			set {
				if ((object.ReferenceEquals(this.AuthKeyField, value) != true)) {
					this.AuthKeyField = value;
					this.RaisePropertyChanged("AuthKey");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Currency {
			get { return this.CurrencyField; }
			set {
				if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
					this.CurrencyField = value;
					this.RaisePropertyChanged("Currency");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string HostAccountNum {
			get { return this.HostAccountNumField; }
			set {
				if ((object.ReferenceEquals(this.HostAccountNumField, value) != true)) {
					this.HostAccountNumField = value;
					this.RaisePropertyChanged("HostAccountNum");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string HostID {
			get { return this.HostIDField; }
			set {
				if ((object.ReferenceEquals(this.HostIDField, value) != true)) {
					this.HostIDField = value;
					this.RaisePropertyChanged("HostID");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string QuoteID {
			get { return this.QuoteIDField; }
			set {
				if ((object.ReferenceEquals(this.QuoteIDField, value) != true)) {
					this.QuoteIDField = value;
					this.RaisePropertyChanged("QuoteID");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string SessionID {
			get { return this.SessionIDField; }
			set {
				if ((object.ReferenceEquals(this.SessionIDField, value) != true)) {
					this.SessionIDField = value;
					this.RaisePropertyChanged("SessionID");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string UserID {
			get { return this.UserIDField; }
			set {
				if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
					this.UserIDField = value;
					this.RaisePropertyChanged("UserID");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Warehouse {
			get { return this.WarehouseField; }
			set {
				if ((object.ReferenceEquals(this.WarehouseField, value) != true)) {
					this.WarehouseField = value;
					this.RaisePropertyChanged("Warehouse");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string[] skus {
			get { return this.skusField; }
			set {
				if ((object.ReferenceEquals(this.skusField, value) != true)) {
					this.skusField = value;
					this.RaisePropertyChanged("skus");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler System.ComponentModel.INotifyPropertyChanged.PropertyChanged;

		protected void RaisePropertyChanged(string propertyName)
		{
			System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChangedEvent;
			if ((!(propertyChanged) == null)) {
				propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"), System.Runtime.Serialization.DataContractAttribute(Name = "clsStockPriceResponse", Namespace = "http://schemas.datacontract.org/2004/07/wsConsumer"), System.SerializableAttribute()]
	public partial class clsStockPriceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
	{

		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private int RequestIDField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private System.DateTime ResponseTimeStampField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string StatusField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool completedField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string currencyField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private wsconsumer.clsStockPriceItem[] itemsField;

		[System.ComponentModel.BrowsableAttribute(false)]
		public System.Runtime.Serialization.ExtensionDataObject System.Runtime.Serialization.IExtensibleDataObject.ExtensionData {
			get { return this.extensionDataField; }
			set { this.extensionDataField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public int RequestID {
			get { return this.RequestIDField; }
			set {
				if ((this.RequestIDField.Equals(value) != true)) {
					this.RequestIDField = value;
					this.RaisePropertyChanged("RequestID");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public System.DateTime ResponseTimeStamp {
			get { return this.ResponseTimeStampField; }
			set {
				if ((this.ResponseTimeStampField.Equals(value) != true)) {
					this.ResponseTimeStampField = value;
					this.RaisePropertyChanged("ResponseTimeStamp");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Status {
			get { return this.StatusField; }
			set {
				if ((object.ReferenceEquals(this.StatusField, value) != true)) {
					this.StatusField = value;
					this.RaisePropertyChanged("Status");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public bool completed {
			get { return this.completedField; }
			set {
				if ((this.completedField.Equals(value) != true)) {
					this.completedField = value;
					this.RaisePropertyChanged("completed");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string currency {
			get { return this.currencyField; }
			set {
				if ((object.ReferenceEquals(this.currencyField, value) != true)) {
					this.currencyField = value;
					this.RaisePropertyChanged("currency");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public wsconsumer.clsStockPriceItem[] items {
			get { return this.itemsField; }
			set {
				if ((object.ReferenceEquals(this.itemsField, value) != true)) {
					this.itemsField = value;
					this.RaisePropertyChanged("items");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler System.ComponentModel.INotifyPropertyChanged.PropertyChanged;

		protected void RaisePropertyChanged(string propertyName)
		{
			System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChangedEvent;
			if ((!(propertyChanged) == null)) {
				propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"), System.Runtime.Serialization.DataContractAttribute(Name = "clsStockPriceItem", Namespace = "http://schemas.datacontract.org/2004/07/wsConsumer"), System.SerializableAttribute()]
	public partial class clsStockPriceItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
	{

		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private float CustomerPriceField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private float ListPriceField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string SKUField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string messageField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string statusField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private wsconsumer.clsShipment[] stockField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string warehouseField;

		[System.ComponentModel.BrowsableAttribute(false)]
		public System.Runtime.Serialization.ExtensionDataObject System.Runtime.Serialization.IExtensibleDataObject.ExtensionData {
			get { return this.extensionDataField; }
			set { this.extensionDataField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public float CustomerPrice {
			get { return this.CustomerPriceField; }
			set {
				if ((this.CustomerPriceField.Equals(value) != true)) {
					this.CustomerPriceField = value;
					this.RaisePropertyChanged("CustomerPrice");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public float ListPrice {
			get { return this.ListPriceField; }
			set {
				if ((this.ListPriceField.Equals(value) != true)) {
					this.ListPriceField = value;
					this.RaisePropertyChanged("ListPrice");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string SKU {
			get { return this.SKUField; }
			set {
				if ((object.ReferenceEquals(this.SKUField, value) != true)) {
					this.SKUField = value;
					this.RaisePropertyChanged("SKU");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string message {
			get { return this.messageField; }
			set {
				if ((object.ReferenceEquals(this.messageField, value) != true)) {
					this.messageField = value;
					this.RaisePropertyChanged("message");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string status {
			get { return this.statusField; }
			set {
				if ((object.ReferenceEquals(this.statusField, value) != true)) {
					this.statusField = value;
					this.RaisePropertyChanged("status");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public wsconsumer.clsShipment[] stock {
			get { return this.stockField; }
			set {
				if ((object.ReferenceEquals(this.stockField, value) != true)) {
					this.stockField = value;
					this.RaisePropertyChanged("stock");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string warehouse {
			get { return this.warehouseField; }
			set {
				if ((object.ReferenceEquals(this.warehouseField, value) != true)) {
					this.warehouseField = value;
					this.RaisePropertyChanged("warehouse");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler System.ComponentModel.INotifyPropertyChanged.PropertyChanged;

		protected void RaisePropertyChanged(string propertyName)
		{
			System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChangedEvent;
			if ((!(propertyChanged) == null)) {
				propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"), System.Runtime.Serialization.DataContractAttribute(Name = "clsShipment", Namespace = "http://schemas.datacontract.org/2004/07/wsConsumer"), System.SerializableAttribute()]
	public partial class clsShipment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
	{

		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private System.DateTime arrivalField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool isCurrentField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private int quantityField;

		[System.ComponentModel.BrowsableAttribute(false)]
		public System.Runtime.Serialization.ExtensionDataObject System.Runtime.Serialization.IExtensibleDataObject.ExtensionData {
			get { return this.extensionDataField; }
			set { this.extensionDataField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public System.DateTime arrival {
			get { return this.arrivalField; }
			set {
				if ((this.arrivalField.Equals(value) != true)) {
					this.arrivalField = value;
					this.RaisePropertyChanged("arrival");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public bool isCurrent {
			get { return this.isCurrentField; }
			set {
				if ((this.isCurrentField.Equals(value) != true)) {
					this.isCurrentField = value;
					this.RaisePropertyChanged("isCurrent");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public int quantity {
			get { return this.quantityField; }
			set {
				if ((this.quantityField.Equals(value) != true)) {
					this.quantityField = value;
					this.RaisePropertyChanged("quantity");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler System.ComponentModel.INotifyPropertyChanged.PropertyChanged;

		protected void RaisePropertyChanged(string propertyName)
		{
			System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChangedEvent;
			if ((!(propertyChanged) == null)) {
				propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"), System.Runtime.Serialization.DataContractAttribute(Name = "clsLogNode", Namespace = "http://schemas.datacontract.org/2004/07/wsConsumer"), System.SerializableAttribute()]
	public partial class clsLogNode : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
	{

		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private int IDField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private wsconsumer.QueueOfint childrenField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string messageField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private int parentField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private int severityField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private System.DateTime timestampField;

		[System.ComponentModel.BrowsableAttribute(false)]
		public System.Runtime.Serialization.ExtensionDataObject System.Runtime.Serialization.IExtensibleDataObject.ExtensionData {
			get { return this.extensionDataField; }
			set { this.extensionDataField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public int ID {
			get { return this.IDField; }
			set {
				if ((this.IDField.Equals(value) != true)) {
					this.IDField = value;
					this.RaisePropertyChanged("ID");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public wsconsumer.QueueOfint children {
			get { return this.childrenField; }
			set {
				if ((object.ReferenceEquals(this.childrenField, value) != true)) {
					this.childrenField = value;
					this.RaisePropertyChanged("children");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string message {
			get { return this.messageField; }
			set {
				if ((object.ReferenceEquals(this.messageField, value) != true)) {
					this.messageField = value;
					this.RaisePropertyChanged("message");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public int parent {
			get { return this.parentField; }
			set {
				if ((this.parentField.Equals(value) != true)) {
					this.parentField = value;
					this.RaisePropertyChanged("parent");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public int severity {
			get { return this.severityField; }
			set {
				if ((this.severityField.Equals(value) != true)) {
					this.severityField = value;
					this.RaisePropertyChanged("severity");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public System.DateTime timestamp {
			get { return this.timestampField; }
			set {
				if ((this.timestampField.Equals(value) != true)) {
					this.timestampField = value;
					this.RaisePropertyChanged("timestamp");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler System.ComponentModel.INotifyPropertyChanged.PropertyChanged;

		protected void RaisePropertyChanged(string propertyName)
		{
			System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChangedEvent;
			if ((!(propertyChanged) == null)) {
				propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"), System.Runtime.Serialization.DataContractAttribute(Name = "QueueOfint", Namespace = "http://schemas.datacontract.org/2004/07/System.Collections.Generic"), System.SerializableAttribute()]
	public partial class QueueOfint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
	{

		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private int[] _arrayField;

		private int _headField;

		private int _sizeField;

		private int _tailField;

		private int _versionField;

		[System.ComponentModel.BrowsableAttribute(false)]
		public System.Runtime.Serialization.ExtensionDataObject System.Runtime.Serialization.IExtensibleDataObject.ExtensionData {
			get { return this.extensionDataField; }
			set { this.extensionDataField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public int[] _array {
			get { return this._arrayField; }
			set {
				if ((object.ReferenceEquals(this._arrayField, value) != true)) {
					this._arrayField = value;
					this.RaisePropertyChanged("_array");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public int _head {
			get { return this._headField; }
			set {
				if ((this._headField.Equals(value) != true)) {
					this._headField = value;
					this.RaisePropertyChanged("_head");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public int _size {
			get { return this._sizeField; }
			set {
				if ((this._sizeField.Equals(value) != true)) {
					this._sizeField = value;
					this.RaisePropertyChanged("_size");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public int _tail {
			get { return this._tailField; }
			set {
				if ((this._tailField.Equals(value) != true)) {
					this._tailField = value;
					this.RaisePropertyChanged("_tail");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public int _version {
			get { return this._versionField; }
			set {
				if ((this._versionField.Equals(value) != true)) {
					this._versionField = value;
					this.RaisePropertyChanged("_version");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler System.ComponentModel.INotifyPropertyChanged.PropertyChanged;

		protected void RaisePropertyChanged(string propertyName)
		{
			System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChangedEvent;
			if ((!(propertyChanged) == null)) {
				propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"), System.Runtime.Serialization.DataContractAttribute(Name = "clslistprice", Namespace = "http://schemas.datacontract.org/2004/07/wsConsumer"), System.SerializableAttribute()]
	public partial class clslistprice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
	{

		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string SKUField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private decimal priceField;

		[System.ComponentModel.BrowsableAttribute(false)]
		public System.Runtime.Serialization.ExtensionDataObject System.Runtime.Serialization.IExtensibleDataObject.ExtensionData {
			get { return this.extensionDataField; }
			set { this.extensionDataField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string SKU {
			get { return this.SKUField; }
			set {
				if ((object.ReferenceEquals(this.SKUField, value) != true)) {
					this.SKUField = value;
					this.RaisePropertyChanged("SKU");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public decimal price {
			get { return this.priceField; }
			set {
				if ((this.priceField.Equals(value) != true)) {
					this.priceField = value;
					this.RaisePropertyChanged("price");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler System.ComponentModel.INotifyPropertyChanged.PropertyChanged;

		protected void RaisePropertyChanged(string propertyName)
		{
			System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChangedEvent;
			if ((!(propertyChanged) == null)) {
				propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"), System.ServiceModel.ServiceContractAttribute(ConfigurationName = "wsconsumer.I_UniTran")]
	public interface I_UniTran
	{

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/AllProducts", ReplyAction = "http://tempuri.org/I_UniTran/AllProductsResponse")]
		string[] AllProducts(string hostID);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/AllProducts", ReplyAction = "http://tempuri.org/I_UniTran/AllProductsResponse")]
		System.Threading.Tasks.Task<string[]> AllProductsAsync(string hostID);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/RequestStockPrices", ReplyAction = "http://tempuri.org/I_UniTran/RequestStockPricesResponse")]
		int RequestStockPrices(wsconsumer.clsStockPriceRequest request);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/RequestStockPrices", ReplyAction = "http://tempuri.org/I_UniTran/RequestStockPricesResponse")]
		System.Threading.Tasks.Task<int> RequestStockPricesAsync(wsconsumer.clsStockPriceRequest request);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/CheckStockPrices", ReplyAction = "http://tempuri.org/I_UniTran/CheckStockPricesResponse")]
		wsconsumer.clsStockPriceResponse CheckStockPrices(int requestid, bool synchronous, int SynchTimeOut);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/CheckStockPrices", ReplyAction = "http://tempuri.org/I_UniTran/CheckStockPricesResponse")]
		System.Threading.Tasks.Task<wsconsumer.clsStockPriceResponse> CheckStockPricesAsync(int requestid, bool synchronous, int SynchTimeOut);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/GetLogNode", ReplyAction = "http://tempuri.org/I_UniTran/GetLogNodeResponse")]
		wsconsumer.clsLogNode GetLogNode(int nodeID);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/GetLogNode", ReplyAction = "http://tempuri.org/I_UniTran/GetLogNodeResponse")]
		System.Threading.Tasks.Task<wsconsumer.clsLogNode> GetLogNodeAsync(int nodeID);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/GetNodeChildren", ReplyAction = "http://tempuri.org/I_UniTran/GetNodeChildrenResponse")]
		wsconsumer.clsLogNode[] GetNodeChildren(int nodeID);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/GetNodeChildren", ReplyAction = "http://tempuri.org/I_UniTran/GetNodeChildrenResponse")]
		System.Threading.Tasks.Task<wsconsumer.clsLogNode[]> GetNodeChildrenAsync(int nodeID);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/find", ReplyAction = "http://tempuri.org/I_UniTran/findResponse")]
		wsconsumer.clsLogNode[] find(int nodeID, string text);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/find", ReplyAction = "http://tempuri.org/I_UniTran/findResponse")]
		System.Threading.Tasks.Task<wsconsumer.clsLogNode[]> findAsync(int nodeID, string text);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/Ancestors", ReplyAction = "http://tempuri.org/I_UniTran/AncestorsResponse")]
		int[] Ancestors(int nodeID);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/Ancestors", ReplyAction = "http://tempuri.org/I_UniTran/AncestorsResponse")]
		System.Threading.Tasks.Task<int[]> AncestorsAsync(int nodeID);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/Prune", ReplyAction = "http://tempuri.org/I_UniTran/PruneResponse")]
		int Prune(int nodeID, bool slash);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/Prune", ReplyAction = "http://tempuri.org/I_UniTran/PruneResponse")]
		System.Threading.Tasks.Task<int> PruneAsync(int nodeID, bool slash);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/BuildRequest", ReplyAction = "http://tempuri.org/I_UniTran/BuildRequestResponse")]
		wsconsumer.clsStockPriceRequest BuildRequest(string hostID, string hostAccountnum, string UserID, string sessionID, string currency, string warehouse, string authkey, string[] Skus, string quoteID, string additionalParameters,
		string app);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/BuildRequest", ReplyAction = "http://tempuri.org/I_UniTran/BuildRequestResponse")]
		System.Threading.Tasks.Task<wsconsumer.clsStockPriceRequest> BuildRequestAsync(string hostID, string hostAccountnum, string UserID, string sessionID, string currency, string warehouse, string authkey, string[] Skus, string quoteID, string additionalParameters,
		string app);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/ListPrices", ReplyAction = "http://tempuri.org/I_UniTran/ListPricesResponse")]
		wsconsumer.clslistprice[] ListPrices(string CountryCode, string currency, string[] HPskus);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/ListPrices", ReplyAction = "http://tempuri.org/I_UniTran/ListPricesResponse")]
		System.Threading.Tasks.Task<wsconsumer.clslistprice[]> ListPricesAsync(string CountryCode, string currency, string[] HPskus);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/hello", ReplyAction = "http://tempuri.org/I_UniTran/helloResponse")]
		string hello();

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/I_UniTran/hello", ReplyAction = "http://tempuri.org/I_UniTran/helloResponse")]
		System.Threading.Tasks.Task<string> helloAsync();
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	public interface I_UniTranChannel : wsconsumer.I_UniTran, System.ServiceModel.IClientChannel
	{
	}

	[System.Diagnostics.DebuggerStepThroughAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	public partial class I_UniTranClient : System.ServiceModel.ClientBase<wsconsumer.I_UniTran>, wsconsumer.I_UniTran
	{

		public I_UniTranClient()
		{
			base.New();
		}

		public I_UniTranClient(string endpointConfigurationName)
		{
			base.New(endpointConfigurationName);
		}

		public I_UniTranClient(string endpointConfigurationName, string remoteAddress)
		{
			base.New(endpointConfigurationName, remoteAddress);
		}

		public I_UniTranClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress)
		{
			base.New(endpointConfigurationName, remoteAddress);
		}

		public I_UniTranClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress)
		{
			base.New(binding, remoteAddress);
		}

		public string[] wsconsumer.I_UniTran.AllProducts(string hostID)
		{
			return base.Channel.AllProducts(hostID);
		}

		public System.Threading.Tasks.Task<string[]> wsconsumer.I_UniTran.AllProductsAsync(string hostID)
		{
			return base.Channel.AllProductsAsync(hostID);
		}

		public int wsconsumer.I_UniTran.RequestStockPrices(wsconsumer.clsStockPriceRequest request)
		{
			return base.Channel.RequestStockPrices(request);
		}

		public System.Threading.Tasks.Task<int> wsconsumer.I_UniTran.RequestStockPricesAsync(wsconsumer.clsStockPriceRequest request)
		{
			return base.Channel.RequestStockPricesAsync(request);
		}

		public wsconsumer.clsStockPriceResponse wsconsumer.I_UniTran.CheckStockPrices(int requestid, bool synchronous, int SynchTimeOut)
		{
			return base.Channel.CheckStockPrices(requestid, synchronous, SynchTimeOut);
		}

		public System.Threading.Tasks.Task<wsconsumer.clsStockPriceResponse> wsconsumer.I_UniTran.CheckStockPricesAsync(int requestid, bool synchronous, int SynchTimeOut)
		{
			return base.Channel.CheckStockPricesAsync(requestid, synchronous, SynchTimeOut);
		}

		public wsconsumer.clsLogNode wsconsumer.I_UniTran.GetLogNode(int nodeID)
		{
			return base.Channel.GetLogNode(nodeID);
		}

		public System.Threading.Tasks.Task<wsconsumer.clsLogNode> wsconsumer.I_UniTran.GetLogNodeAsync(int nodeID)
		{
			return base.Channel.GetLogNodeAsync(nodeID);
		}

		public wsconsumer.clsLogNode[] wsconsumer.I_UniTran.GetNodeChildren(int nodeID)
		{
			return base.Channel.GetNodeChildren(nodeID);
		}

		public System.Threading.Tasks.Task<wsconsumer.clsLogNode[]> wsconsumer.I_UniTran.GetNodeChildrenAsync(int nodeID)
		{
			return base.Channel.GetNodeChildrenAsync(nodeID);
		}

		public wsconsumer.clsLogNode[] wsconsumer.I_UniTran.find(int nodeID, string text)
		{
			return base.Channel.find(nodeID, text);
		}

		public System.Threading.Tasks.Task<wsconsumer.clsLogNode[]> wsconsumer.I_UniTran.findAsync(int nodeID, string text)
		{
			return base.Channel.findAsync(nodeID, text);
		}

		public int[] wsconsumer.I_UniTran.Ancestors(int nodeID)
		{
			return base.Channel.Ancestors(nodeID);
		}

		public System.Threading.Tasks.Task<int[]> wsconsumer.I_UniTran.AncestorsAsync(int nodeID)
		{
			return base.Channel.AncestorsAsync(nodeID);
		}

		public int wsconsumer.I_UniTran.Prune(int nodeID, bool slash)
		{
			return base.Channel.Prune(nodeID, slash);
		}

		public System.Threading.Tasks.Task<int> wsconsumer.I_UniTran.PruneAsync(int nodeID, bool slash)
		{
			return base.Channel.PruneAsync(nodeID, slash);
		}

		public wsconsumer.clsStockPriceRequest wsconsumer.I_UniTran.BuildRequest(string hostID, string hostAccountnum, string UserID, string sessionID, string currency, string warehouse, string authkey, string[] Skus, string quoteID, string additionalParameters,
		string app)
		{
			return base.Channel.BuildRequest(hostID, hostAccountnum, UserID, sessionID, currency, warehouse, authkey, Skus, quoteID, additionalParameters,
			app);
		}

		public System.Threading.Tasks.Task<wsconsumer.clsStockPriceRequest> wsconsumer.I_UniTran.BuildRequestAsync(string hostID, string hostAccountnum, string UserID, string sessionID, string currency, string warehouse, string authkey, string[] Skus, string quoteID, string additionalParameters,
		string app)
		{
			return base.Channel.BuildRequestAsync(hostID, hostAccountnum, UserID, sessionID, currency, warehouse, authkey, Skus, quoteID, additionalParameters,
			app);
		}

		public wsconsumer.clslistprice[] wsconsumer.I_UniTran.ListPrices(string CountryCode, string currency, string[] HPskus)
		{
			return base.Channel.ListPrices(CountryCode, currency, HPskus);
		}

		public System.Threading.Tasks.Task<wsconsumer.clslistprice[]> wsconsumer.I_UniTran.ListPricesAsync(string CountryCode, string currency, string[] HPskus)
		{
			return base.Channel.ListPricesAsync(CountryCode, currency, HPskus);
		}

		public string wsconsumer.I_UniTran.hello()
		{
			return base.Channel.hello;
		}

		public System.Threading.Tasks.Task<string> wsconsumer.I_UniTran.helloAsync()
		{
			return base.Channel.helloAsync;
		}
	}
}
