'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace wsconsumer
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="clsStockPriceRequest", [Namespace]:="http://schemas.datacontract.org/2004/07/wsConsumer"),  _
     System.SerializableAttribute()>  _
    Partial Public Class clsStockPriceRequest
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AdditionalParamsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AppField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AuthKeyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CurrencyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HostAccountNumField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HostIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QuoteIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SessionIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private WarehouseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private skusField() As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AdditionalParams() As String
            Get
                Return Me.AdditionalParamsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AdditionalParamsField, value) <> true) Then
                    Me.AdditionalParamsField = value
                    Me.RaisePropertyChanged("AdditionalParams")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property App() As String
            Get
                Return Me.AppField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AppField, value) <> true) Then
                    Me.AppField = value
                    Me.RaisePropertyChanged("App")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AuthKey() As String
            Get
                Return Me.AuthKeyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AuthKeyField, value) <> true) Then
                    Me.AuthKeyField = value
                    Me.RaisePropertyChanged("AuthKey")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Currency() As String
            Get
                Return Me.CurrencyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CurrencyField, value) <> true) Then
                    Me.CurrencyField = value
                    Me.RaisePropertyChanged("Currency")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HostAccountNum() As String
            Get
                Return Me.HostAccountNumField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HostAccountNumField, value) <> true) Then
                    Me.HostAccountNumField = value
                    Me.RaisePropertyChanged("HostAccountNum")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HostID() As String
            Get
                Return Me.HostIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HostIDField, value) <> true) Then
                    Me.HostIDField = value
                    Me.RaisePropertyChanged("HostID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property QuoteID() As String
            Get
                Return Me.QuoteIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.QuoteIDField, value) <> true) Then
                    Me.QuoteIDField = value
                    Me.RaisePropertyChanged("QuoteID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SessionID() As String
            Get
                Return Me.SessionIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SessionIDField, value) <> true) Then
                    Me.SessionIDField = value
                    Me.RaisePropertyChanged("SessionID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserID() As String
            Get
                Return Me.UserIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserIDField, value) <> true) Then
                    Me.UserIDField = value
                    Me.RaisePropertyChanged("UserID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Warehouse() As String
            Get
                Return Me.WarehouseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WarehouseField, value) <> true) Then
                    Me.WarehouseField = value
                    Me.RaisePropertyChanged("Warehouse")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property skus() As String()
            Get
                Return Me.skusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.skusField, value) <> true) Then
                    Me.skusField = value
                    Me.RaisePropertyChanged("skus")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="clsStockPriceResponse", [Namespace]:="http://schemas.datacontract.org/2004/07/wsConsumer"),  _
     System.SerializableAttribute()>  _
    Partial Public Class clsStockPriceResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RequestIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ResponseTimeStampField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private completedField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private currencyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private itemsField() As wsconsumer.clsStockPriceItem
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RequestID() As Integer
            Get
                Return Me.RequestIDField
            End Get
            Set
                If (Me.RequestIDField.Equals(value) <> true) Then
                    Me.RequestIDField = value
                    Me.RaisePropertyChanged("RequestID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ResponseTimeStamp() As Date
            Get
                Return Me.ResponseTimeStampField
            End Get
            Set
                If (Me.ResponseTimeStampField.Equals(value) <> true) Then
                    Me.ResponseTimeStampField = value
                    Me.RaisePropertyChanged("ResponseTimeStamp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As String
            Get
                Return Me.StatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusField, value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property completed() As Boolean
            Get
                Return Me.completedField
            End Get
            Set
                If (Me.completedField.Equals(value) <> true) Then
                    Me.completedField = value
                    Me.RaisePropertyChanged("completed")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property currency() As String
            Get
                Return Me.currencyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.currencyField, value) <> true) Then
                    Me.currencyField = value
                    Me.RaisePropertyChanged("currency")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property items() As wsconsumer.clsStockPriceItem()
            Get
                Return Me.itemsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.itemsField, value) <> true) Then
                    Me.itemsField = value
                    Me.RaisePropertyChanged("items")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="clsStockPriceItem", [Namespace]:="http://schemas.datacontract.org/2004/07/wsConsumer"),  _
     System.SerializableAttribute()>  _
    Partial Public Class clsStockPriceItem
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomerPriceField As Single
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ListPriceField As Single
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SKUField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private messageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private statusField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private stockField() As wsconsumer.clsShipment
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private warehouseField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustomerPrice() As Single
            Get
                Return Me.CustomerPriceField
            End Get
            Set
                If (Me.CustomerPriceField.Equals(value) <> true) Then
                    Me.CustomerPriceField = value
                    Me.RaisePropertyChanged("CustomerPrice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ListPrice() As Single
            Get
                Return Me.ListPriceField
            End Get
            Set
                If (Me.ListPriceField.Equals(value) <> true) Then
                    Me.ListPriceField = value
                    Me.RaisePropertyChanged("ListPrice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SKU() As String
            Get
                Return Me.SKUField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SKUField, value) <> true) Then
                    Me.SKUField = value
                    Me.RaisePropertyChanged("SKU")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.messageField, value) <> true) Then
                    Me.messageField = value
                    Me.RaisePropertyChanged("message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.statusField, value) <> true) Then
                    Me.statusField = value
                    Me.RaisePropertyChanged("status")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property stock() As wsconsumer.clsShipment()
            Get
                Return Me.stockField
            End Get
            Set
                If (Object.ReferenceEquals(Me.stockField, value) <> true) Then
                    Me.stockField = value
                    Me.RaisePropertyChanged("stock")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property warehouse() As String
            Get
                Return Me.warehouseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.warehouseField, value) <> true) Then
                    Me.warehouseField = value
                    Me.RaisePropertyChanged("warehouse")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="clsShipment", [Namespace]:="http://schemas.datacontract.org/2004/07/wsConsumer"),  _
     System.SerializableAttribute()>  _
    Partial Public Class clsShipment
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private arrivalField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private isCurrentField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private quantityField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property arrival() As Date
            Get
                Return Me.arrivalField
            End Get
            Set
                If (Me.arrivalField.Equals(value) <> true) Then
                    Me.arrivalField = value
                    Me.RaisePropertyChanged("arrival")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property isCurrent() As Boolean
            Get
                Return Me.isCurrentField
            End Get
            Set
                If (Me.isCurrentField.Equals(value) <> true) Then
                    Me.isCurrentField = value
                    Me.RaisePropertyChanged("isCurrent")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property quantity() As Integer
            Get
                Return Me.quantityField
            End Get
            Set
                If (Me.quantityField.Equals(value) <> true) Then
                    Me.quantityField = value
                    Me.RaisePropertyChanged("quantity")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="clsLogNode", [Namespace]:="http://schemas.datacontract.org/2004/07/wsConsumer"),  _
     System.SerializableAttribute()>  _
    Partial Public Class clsLogNode
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private childrenField As wsconsumer.QueueOfint
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private messageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private parentField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private severityField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private timestampField As Date
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As Integer
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property children() As wsconsumer.QueueOfint
            Get
                Return Me.childrenField
            End Get
            Set
                If (Object.ReferenceEquals(Me.childrenField, value) <> true) Then
                    Me.childrenField = value
                    Me.RaisePropertyChanged("children")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.messageField, value) <> true) Then
                    Me.messageField = value
                    Me.RaisePropertyChanged("message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property parent() As Integer
            Get
                Return Me.parentField
            End Get
            Set
                If (Me.parentField.Equals(value) <> true) Then
                    Me.parentField = value
                    Me.RaisePropertyChanged("parent")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property severity() As Integer
            Get
                Return Me.severityField
            End Get
            Set
                If (Me.severityField.Equals(value) <> true) Then
                    Me.severityField = value
                    Me.RaisePropertyChanged("severity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property timestamp() As Date
            Get
                Return Me.timestampField
            End Get
            Set
                If (Me.timestampField.Equals(value) <> true) Then
                    Me.timestampField = value
                    Me.RaisePropertyChanged("timestamp")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="QueueOfint", [Namespace]:="http://schemas.datacontract.org/2004/07/System.Collections.Generic"),  _
     System.SerializableAttribute()>  _
    Partial Public Class QueueOfint
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private _arrayField() As Integer
        
        Private _headField As Integer
        
        Private _sizeField As Integer
        
        Private _tailField As Integer
        
        Private _versionField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property _array() As Integer()
            Get
                Return Me._arrayField
            End Get
            Set
                If (Object.ReferenceEquals(Me._arrayField, value) <> true) Then
                    Me._arrayField = value
                    Me.RaisePropertyChanged("_array")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property _head() As Integer
            Get
                Return Me._headField
            End Get
            Set
                If (Me._headField.Equals(value) <> true) Then
                    Me._headField = value
                    Me.RaisePropertyChanged("_head")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property _size() As Integer
            Get
                Return Me._sizeField
            End Get
            Set
                If (Me._sizeField.Equals(value) <> true) Then
                    Me._sizeField = value
                    Me.RaisePropertyChanged("_size")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property _tail() As Integer
            Get
                Return Me._tailField
            End Get
            Set
                If (Me._tailField.Equals(value) <> true) Then
                    Me._tailField = value
                    Me.RaisePropertyChanged("_tail")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property _version() As Integer
            Get
                Return Me._versionField
            End Get
            Set
                If (Me._versionField.Equals(value) <> true) Then
                    Me._versionField = value
                    Me.RaisePropertyChanged("_version")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="clslistprice", [Namespace]:="http://schemas.datacontract.org/2004/07/wsConsumer"),  _
     System.SerializableAttribute()>  _
    Partial Public Class clslistprice
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SKUField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private priceField As Decimal
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SKU() As String
            Get
                Return Me.SKUField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SKUField, value) <> true) Then
                    Me.SKUField = value
                    Me.RaisePropertyChanged("SKU")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property price() As Decimal
            Get
                Return Me.priceField
            End Get
            Set
                If (Me.priceField.Equals(value) <> true) Then
                    Me.priceField = value
                    Me.RaisePropertyChanged("price")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="wsconsumer.I_UniTran")>  _
    Public Interface I_UniTran
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/AllProducts", ReplyAction:="http://tempuri.org/I_UniTran/AllProductsResponse")>  _
        Function AllProducts(ByVal hostID As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/AllProducts", ReplyAction:="http://tempuri.org/I_UniTran/AllProductsResponse")>  _
        Function AllProductsAsync(ByVal hostID As String) As System.Threading.Tasks.Task(Of String())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/RequestStockPrices", ReplyAction:="http://tempuri.org/I_UniTran/RequestStockPricesResponse")>  _
        Function RequestStockPrices(ByVal request As wsconsumer.clsStockPriceRequest) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/RequestStockPrices", ReplyAction:="http://tempuri.org/I_UniTran/RequestStockPricesResponse")>  _
        Function RequestStockPricesAsync(ByVal request As wsconsumer.clsStockPriceRequest) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/CheckStockPrices", ReplyAction:="http://tempuri.org/I_UniTran/CheckStockPricesResponse")>  _
        Function CheckStockPrices(ByVal requestid As Integer, ByVal synchronous As Boolean, ByVal SynchTimeOut As Integer) As wsconsumer.clsStockPriceResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/CheckStockPrices", ReplyAction:="http://tempuri.org/I_UniTran/CheckStockPricesResponse")>  _
        Function CheckStockPricesAsync(ByVal requestid As Integer, ByVal synchronous As Boolean, ByVal SynchTimeOut As Integer) As System.Threading.Tasks.Task(Of wsconsumer.clsStockPriceResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/GetLogNode", ReplyAction:="http://tempuri.org/I_UniTran/GetLogNodeResponse")>  _
        Function GetLogNode(ByVal nodeID As Integer) As wsconsumer.clsLogNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/GetLogNode", ReplyAction:="http://tempuri.org/I_UniTran/GetLogNodeResponse")>  _
        Function GetLogNodeAsync(ByVal nodeID As Integer) As System.Threading.Tasks.Task(Of wsconsumer.clsLogNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/GetNodeChildren", ReplyAction:="http://tempuri.org/I_UniTran/GetNodeChildrenResponse")>  _
        Function GetNodeChildren(ByVal nodeID As Integer) As wsconsumer.clsLogNode()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/GetNodeChildren", ReplyAction:="http://tempuri.org/I_UniTran/GetNodeChildrenResponse")>  _
        Function GetNodeChildrenAsync(ByVal nodeID As Integer) As System.Threading.Tasks.Task(Of wsconsumer.clsLogNode())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/find", ReplyAction:="http://tempuri.org/I_UniTran/findResponse")>  _
        Function find(ByVal nodeID As Integer, ByVal text As String) As wsconsumer.clsLogNode()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/find", ReplyAction:="http://tempuri.org/I_UniTran/findResponse")>  _
        Function findAsync(ByVal nodeID As Integer, ByVal text As String) As System.Threading.Tasks.Task(Of wsconsumer.clsLogNode())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/Ancestors", ReplyAction:="http://tempuri.org/I_UniTran/AncestorsResponse")>  _
        Function Ancestors(ByVal nodeID As Integer) As Integer()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/Ancestors", ReplyAction:="http://tempuri.org/I_UniTran/AncestorsResponse")>  _
        Function AncestorsAsync(ByVal nodeID As Integer) As System.Threading.Tasks.Task(Of Integer())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/Prune", ReplyAction:="http://tempuri.org/I_UniTran/PruneResponse")>  _
        Function Prune(ByVal nodeID As Integer, ByVal slash As Boolean) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/Prune", ReplyAction:="http://tempuri.org/I_UniTran/PruneResponse")>  _
        Function PruneAsync(ByVal nodeID As Integer, ByVal slash As Boolean) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/BuildRequest", ReplyAction:="http://tempuri.org/I_UniTran/BuildRequestResponse")>  _
        Function BuildRequest(ByVal hostID As String, ByVal hostAccountnum As String, ByVal UserID As String, ByVal sessionID As String, ByVal currency As String, ByVal warehouse As String, ByVal authkey As String, ByVal Skus() As String, ByVal quoteID As String, ByVal additionalParameters As String, ByVal app As String) As wsconsumer.clsStockPriceRequest
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/BuildRequest", ReplyAction:="http://tempuri.org/I_UniTran/BuildRequestResponse")>  _
        Function BuildRequestAsync(ByVal hostID As String, ByVal hostAccountnum As String, ByVal UserID As String, ByVal sessionID As String, ByVal currency As String, ByVal warehouse As String, ByVal authkey As String, ByVal Skus() As String, ByVal quoteID As String, ByVal additionalParameters As String, ByVal app As String) As System.Threading.Tasks.Task(Of wsconsumer.clsStockPriceRequest)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/ListPrices", ReplyAction:="http://tempuri.org/I_UniTran/ListPricesResponse")>  _
        Function ListPrices(ByVal CountryCode As String, ByVal currency As String, ByVal HPskus() As String) As wsconsumer.clslistprice()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/ListPrices", ReplyAction:="http://tempuri.org/I_UniTran/ListPricesResponse")>  _
        Function ListPricesAsync(ByVal CountryCode As String, ByVal currency As String, ByVal HPskus() As String) As System.Threading.Tasks.Task(Of wsconsumer.clslistprice())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/hello", ReplyAction:="http://tempuri.org/I_UniTran/helloResponse")>  _
        Function hello() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/I_UniTran/hello", ReplyAction:="http://tempuri.org/I_UniTran/helloResponse")>  _
        Function helloAsync() As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface I_UniTranChannel
        Inherits wsconsumer.I_UniTran, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class I_UniTranClient
        Inherits System.ServiceModel.ClientBase(Of wsconsumer.I_UniTran)
        Implements wsconsumer.I_UniTran
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function AllProducts(ByVal hostID As String) As String() Implements wsconsumer.I_UniTran.AllProducts
            Return MyBase.Channel.AllProducts(hostID)
        End Function
        
        Public Function AllProductsAsync(ByVal hostID As String) As System.Threading.Tasks.Task(Of String()) Implements wsconsumer.I_UniTran.AllProductsAsync
            Return MyBase.Channel.AllProductsAsync(hostID)
        End Function
        
        Public Function RequestStockPrices(ByVal request As wsconsumer.clsStockPriceRequest) As Integer Implements wsconsumer.I_UniTran.RequestStockPrices
            Return MyBase.Channel.RequestStockPrices(request)
        End Function
        
        Public Function RequestStockPricesAsync(ByVal request As wsconsumer.clsStockPriceRequest) As System.Threading.Tasks.Task(Of Integer) Implements wsconsumer.I_UniTran.RequestStockPricesAsync
            Return MyBase.Channel.RequestStockPricesAsync(request)
        End Function
        
        Public Function CheckStockPrices(ByVal requestid As Integer, ByVal synchronous As Boolean, ByVal SynchTimeOut As Integer) As wsconsumer.clsStockPriceResponse Implements wsconsumer.I_UniTran.CheckStockPrices
            Return MyBase.Channel.CheckStockPrices(requestid, synchronous, SynchTimeOut)
        End Function
        
        Public Function CheckStockPricesAsync(ByVal requestid As Integer, ByVal synchronous As Boolean, ByVal SynchTimeOut As Integer) As System.Threading.Tasks.Task(Of wsconsumer.clsStockPriceResponse) Implements wsconsumer.I_UniTran.CheckStockPricesAsync
            Return MyBase.Channel.CheckStockPricesAsync(requestid, synchronous, SynchTimeOut)
        End Function
        
        Public Function GetLogNode(ByVal nodeID As Integer) As wsconsumer.clsLogNode Implements wsconsumer.I_UniTran.GetLogNode
            Return MyBase.Channel.GetLogNode(nodeID)
        End Function
        
        Public Function GetLogNodeAsync(ByVal nodeID As Integer) As System.Threading.Tasks.Task(Of wsconsumer.clsLogNode) Implements wsconsumer.I_UniTran.GetLogNodeAsync
            Return MyBase.Channel.GetLogNodeAsync(nodeID)
        End Function
        
        Public Function GetNodeChildren(ByVal nodeID As Integer) As wsconsumer.clsLogNode() Implements wsconsumer.I_UniTran.GetNodeChildren
            Return MyBase.Channel.GetNodeChildren(nodeID)
        End Function
        
        Public Function GetNodeChildrenAsync(ByVal nodeID As Integer) As System.Threading.Tasks.Task(Of wsconsumer.clsLogNode()) Implements wsconsumer.I_UniTran.GetNodeChildrenAsync
            Return MyBase.Channel.GetNodeChildrenAsync(nodeID)
        End Function
        
        Public Function find(ByVal nodeID As Integer, ByVal text As String) As wsconsumer.clsLogNode() Implements wsconsumer.I_UniTran.find
            Return MyBase.Channel.find(nodeID, text)
        End Function
        
        Public Function findAsync(ByVal nodeID As Integer, ByVal text As String) As System.Threading.Tasks.Task(Of wsconsumer.clsLogNode()) Implements wsconsumer.I_UniTran.findAsync
            Return MyBase.Channel.findAsync(nodeID, text)
        End Function
        
        Public Function Ancestors(ByVal nodeID As Integer) As Integer() Implements wsconsumer.I_UniTran.Ancestors
            Return MyBase.Channel.Ancestors(nodeID)
        End Function
        
        Public Function AncestorsAsync(ByVal nodeID As Integer) As System.Threading.Tasks.Task(Of Integer()) Implements wsconsumer.I_UniTran.AncestorsAsync
            Return MyBase.Channel.AncestorsAsync(nodeID)
        End Function
        
        Public Function Prune(ByVal nodeID As Integer, ByVal slash As Boolean) As Integer Implements wsconsumer.I_UniTran.Prune
            Return MyBase.Channel.Prune(nodeID, slash)
        End Function
        
        Public Function PruneAsync(ByVal nodeID As Integer, ByVal slash As Boolean) As System.Threading.Tasks.Task(Of Integer) Implements wsconsumer.I_UniTran.PruneAsync
            Return MyBase.Channel.PruneAsync(nodeID, slash)
        End Function
        
        Public Function BuildRequest(ByVal hostID As String, ByVal hostAccountnum As String, ByVal UserID As String, ByVal sessionID As String, ByVal currency As String, ByVal warehouse As String, ByVal authkey As String, ByVal Skus() As String, ByVal quoteID As String, ByVal additionalParameters As String, ByVal app As String) As wsconsumer.clsStockPriceRequest Implements wsconsumer.I_UniTran.BuildRequest
            Return MyBase.Channel.BuildRequest(hostID, hostAccountnum, UserID, sessionID, currency, warehouse, authkey, Skus, quoteID, additionalParameters, app)
        End Function
        
        Public Function BuildRequestAsync(ByVal hostID As String, ByVal hostAccountnum As String, ByVal UserID As String, ByVal sessionID As String, ByVal currency As String, ByVal warehouse As String, ByVal authkey As String, ByVal Skus() As String, ByVal quoteID As String, ByVal additionalParameters As String, ByVal app As String) As System.Threading.Tasks.Task(Of wsconsumer.clsStockPriceRequest) Implements wsconsumer.I_UniTran.BuildRequestAsync
            Return MyBase.Channel.BuildRequestAsync(hostID, hostAccountnum, UserID, sessionID, currency, warehouse, authkey, Skus, quoteID, additionalParameters, app)
        End Function
        
        Public Function ListPrices(ByVal CountryCode As String, ByVal currency As String, ByVal HPskus() As String) As wsconsumer.clslistprice() Implements wsconsumer.I_UniTran.ListPrices
            Return MyBase.Channel.ListPrices(CountryCode, currency, HPskus)
        End Function
        
        Public Function ListPricesAsync(ByVal CountryCode As String, ByVal currency As String, ByVal HPskus() As String) As System.Threading.Tasks.Task(Of wsconsumer.clslistprice()) Implements wsconsumer.I_UniTran.ListPricesAsync
            Return MyBase.Channel.ListPricesAsync(CountryCode, currency, HPskus)
        End Function
        
        Public Function hello() As String Implements wsconsumer.I_UniTran.hello
            Return MyBase.Channel.hello
        End Function
        
        Public Function helloAsync() As System.Threading.Tasks.Task(Of String) Implements wsconsumer.I_UniTran.helloAsync
            Return MyBase.Channel.helloAsync
        End Function
    End Class
End Namespace
