//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Sync
{

	///<summary>
	///txtSKUList control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.TextBox txtSKUList;
	///<summary>
	///btnDoImport control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.Button btnDoImport;
	///<summary>
	///Button1 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>
	protected global::System.Web.UI.WebControls.Button Button1;
}
