/****** Object:  Table [dbo].[Culture]    Script Date: 21/01/2015 11:04:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Culture](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CultureCode] [nvarchar](255) NULL,
	[Name] [nvarchar](255) NULL,
	[DefaultCulture] [bit] NOT NULL,
	[Visible] [bit] NOT NULL,
 CONSTRAINT [PK_Culture] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET IDENTITY_INSERT [dbo].[Culture] ON 

INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (1, N'af-ZA', N'Afrikaans - South Africa', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (2, N'sq-AL', N'Albanian - Albania', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (3, N'ar-DZ', N'Arabic - Algeria', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (4, N'ar-BH', N'Arabic - Bahrain', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (5, N'ar-EG', N'Arabic - Egypt', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (6, N'ar-IQ', N'Arabic - Iraq', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (7, N'ar-JO', N'Arabic - Jordan', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (8, N'ar-KW', N'Arabic - Kuwait', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (9, N'ar-LB', N'Arabic - Lebanon', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (10, N'ar-LY', N'Arabic - Libya', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (11, N'ar-MA', N'Arabic - Morocco', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (12, N'ar-OM', N'Arabic - Oman', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (13, N'ar-QA', N'Arabic - Qatar', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (14, N'ar-SA', N'Arabic - Saudi Arabia', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (15, N'ar-SY', N'Arabic - Syria', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (16, N'ar-TN', N'Arabic - Tunisia', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (17, N'ar-AE', N'Arabic - United Arab Emirates', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (18, N'ar-YE', N'Arabic - Yemen', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (19, N'hy-AM', N'Armenian - Armenia', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (20, N'Cy-az-AZ', N'Azeri (Cyrillic) - Azerbaijan', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (21, N'Lt-az-AZ', N'Azeri (Latin) - Azerbaijan', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (22, N'eu-ES', N'Basque - Basque', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (23, N'be-BY', N'Belarusian - Belarus', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (24, N'bg-BG', N'Bulgarian - Bulgaria', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (25, N'ca-ES', N'Catalan - Catalan', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (26, N'zh-CN', N'Chinese - China', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (27, N'zh-HK', N'Chinese - Hong Kong SAR', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (28, N'zh-MO', N'Chinese - Macau SAR', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (29, N'zh-SG', N'Chinese - Singapore', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (30, N'zh-TW', N'Chinese - Taiwan', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (31, N'zh-CHS', N'Chinese (Simplified)', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (32, N'zh-CHT', N'Chinese (Traditional)', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (33, N'hr-HR', N'Croatian - Croatia', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (34, N'cs-CZ', N'Czech - Czech Republic', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (35, N'da-DK', N'Danish - Denmark', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (36, N'div-MV', N'Dhivehi - Maldives', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (37, N'nl-BE', N'Dutch - Belgium', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (38, N'nl-NL', N'Dutch - The Netherlands', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (39, N'en-AU', N'English - Australia', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (40, N'en-BZ', N'English - Belize', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (41, N'en-CA', N'English - Canada', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (42, N'en-CB', N'English - Caribbean', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (43, N'en-IE', N'English - Ireland', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (44, N'en-JM', N'English - Jamaica', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (45, N'en-NZ', N'English - New Zealand', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (46, N'en-PH', N'English - Philippines', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (47, N'en-ZA', N'English - South Africa', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (48, N'en-TT', N'English - Trinidad and Tobago', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (49, N'en-GB', N'English - United Kingdom', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (50, N'en-US', N'English - United States', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (51, N'en-ZW', N'English - Zimbabwe', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (52, N'et-EE', N'Estonian - Estonia', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (53, N'fo-FO', N'Faroese - Faroe Islands', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (54, N'fa-IR', N'Farsi - Iran', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (55, N'fi-FI', N'Finnish - Finland', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (56, N'fr-BE', N'French - Belgium', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (57, N'fr-CA', N'French - Canada', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (58, N'fr-FR', N'French - France', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (59, N'fr-LU', N'French - Luxembourg', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (60, N'fr-MC', N'French - Monaco', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (61, N'fr-CH', N'French - Switzerland', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (62, N'gl-ES', N'Galician - Galician', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (63, N'ka-GE', N'Georgian - Georgia', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (64, N'de-AT', N'German - Austria', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (65, N'de-DE', N'German - Germany', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (66, N'de-LI', N'German - Liechtenstein', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (67, N'de-LU', N'German - Luxembourg', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (68, N'de-CH', N'German - Switzerland', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (69, N'el-GR', N'Greek - Greece', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (70, N'gu-IN', N'Gujarati - India', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (71, N'he-IL', N'Hebrew - Israel', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (72, N'hi-IN', N'Hindi - India', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (73, N'hu-HU', N'Hungarian - Hungary', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (74, N'is-IS', N'Icelandic - Iceland', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (75, N'id-ID', N'Indonesian - Indonesia', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (76, N'it-IT', N'Italian - Italy', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (77, N'it-CH', N'Italian - Switzerland', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (78, N'ja-JP', N'Japanese - Japan', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (79, N'kn-IN', N'Kannada - India', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (80, N'kk-KZ', N'Kazakh - Kazakhstan', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (81, N'kok-IN', N'Konkani - India', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (82, N'ko-KR', N'Korean - Korea', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (83, N'ky-KZ', N'Kyrgyz - Kazakhstan', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (84, N'lv-LV', N'Latvian - Latvia', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (85, N'lt-LT', N'Lithuanian - Lithuania', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (86, N'mk-MK', N'Macedonian (FYROM)', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (87, N'ms-BN', N'Malay - Brunei', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (88, N'ms-MY', N'Malay - Malaysia', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (89, N'mr-IN', N'Marathi - India', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (90, N'mn-MN', N'Mongolian - Mongolia', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (91, N'nb-NO', N'Norwegian (Bokmål) - Norway', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (92, N'nn-NO', N'Norwegian (Nynorsk) - Norway', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (93, N'pl-PL', N'Polish - Poland', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (94, N'pt-BR', N'Portuguese - Brazil', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (95, N'pt-PT', N'Portuguese - Portugal', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (96, N'pa-IN', N'Punjabi - India', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (97, N'ro-RO', N'Romanian - Romania', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (98, N'ru-RU', N'Russian - Russia', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (99, N'sa-IN', N'Sanskrit - India', 0, 0)
GO
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (100, N'Cy-sr-SP', N'Serbian (Cyrillic) - Serbia', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (101, N'Lt-sr-SP', N'Serbian (Latin) - Serbia', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (102, N'sk-SK', N'Slovak - Slovakia', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (103, N'sl-SI', N'Slovenian - Slovenia', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (104, N'es-AR', N'Spanish - Argentina', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (105, N'es-BO', N'Spanish - Bolivia', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (106, N'es-CL', N'Spanish - Chile', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (107, N'es-CO', N'Spanish - Colombia', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (108, N'es-CR', N'Spanish - Costa Rica', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (109, N'es-DO', N'Spanish - Dominican Republic', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (110, N'es-EC', N'Spanish - Ecuador', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (111, N'es-SV', N'Spanish - El Salvador', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (112, N'es-GT', N'Spanish - Guatemala', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (113, N'es-HN', N'Spanish - Honduras', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (114, N'es-MX', N'Spanish - Mexico', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (115, N'es-NI', N'Spanish - Nicaragua', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (116, N'es-PA', N'Spanish - Panama', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (117, N'es-PY', N'Spanish - Paraguay', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (118, N'es-PE', N'Spanish - Peru', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (119, N'es-PR', N'Spanish - Puerto Rico', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (120, N'es-ES', N'Spanish - Spain', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (121, N'es-UY', N'Spanish - Uruguay', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (122, N'es-VE', N'Spanish - Venezuela', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (123, N'sw-KE', N'Swahili - Kenya', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (124, N'sv-FI', N'Swedish - Finland', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (125, N'sv-SE', N'Swedish - Sweden', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (126, N'syr-SY', N'Syriac - Syria', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (127, N'ta-IN', N'Tamil - India', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (128, N'tt-RU', N'Tatar - Russia', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (129, N'te-IN', N'Telugu - India', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (130, N'th-TH', N'Thai - Thailand', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (131, N'tr-TR', N'Turkish - Turkey', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (132, N'uk-UA', N'Ukrainian - Ukraine', 1, 1)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (133, N'ur-PK', N'Urdu - Pakistan', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (134, N'Cy-uz-UZ', N'Uzbek (Cyrillic) - Uzbekistan', 1, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (135, N'Lt-uz-UZ', N'Uzbek (Latin) - Uzbekistan', 0, 0)
INSERT [dbo].[Culture] ([ID], [CultureCode], [Name], [DefaultCulture], [Visible]) VALUES (136, N'vi-VN', N'Vietnamese - Vietnam', 1, 0)
SET IDENTITY_INSERT [dbo].[Culture] OFF
ALTER TABLE [dbo].[Culture] ADD  CONSTRAINT [DF_Culture_DefaultCulture]  DEFAULT ((0)) FOR [DefaultCulture]
GO
ALTER TABLE [dbo].[Culture] ADD  CONSTRAINT [DF_Culture_Visible]  DEFAULT ((0)) FOR [Visible]
GO
